### ISSUE TITLE
Overriding startIcon and endIcon

### ISSUE THREAD

**Issue by ChrilleSchappe** [mpetazzoni/leaflet-gpx#167]
In the documentation:
"startIcon is used for the marker at the beginning of the GPX track;
endIcon is used for the marker at the end of the GPX track;
wptIcons and wptTypeIcons are mappings of waypoint symbols and types to the icon you want to use for each;
pointMatchers is an array of custom point matchers and their respective icon (see below);
You can also override any of those to null to disable the corresponding marker altogether."

Setting startIcon and/or endIcon to null will result in that the gpx layer will not be  constructed.

**Comment by mpetazzoni** [comment]
@ChrilleSchappe Do you mind sharing your code snippet?

**Comment by ChrilleSchappe** [comment]
var LineColor = LineColors [GI];
	    G[GI] = new L.GPX(gpx, {
		async: true,
		polyline_options:{
		    color: LineColor
		},
		markers: {
		    startIcon: null, 		   // startIcon: SIL,
		    endIcon: null,                  // endIcon: FIL,
		},
		marker_options: {
		    iconSize: [100, 100],
		    iconAnchor: [50, 100],
		}
	    }).on('loaded', function(e) {
		e.target.addTo(map);
		map.fitBounds(e.target.getBounds());
	    });

If I have my own icons (SIL and FIL) it works fine but if I use null, this happens (js console) :

gpx.min.js:1 Uncaught TypeError: Cannot convert undefined or null to object
    at Function.entries (<anonymous>)
    at e._prepare_markers (gpx.min.js:1:6449)
    at gpx.min.js:1:6686
    at Array.forEach (<anonymous>)
    at e._prepare_markers (gpx.min.js:1:6460)
    at e.initialize (gpx.min.js:1:1089)
    at new e (Class.js:24:20)
    at ThisFirst (ShowMap.php:139:14)
    at onload (ShowMap.php:1087:29)

**Comment by mpetazzoni** [comment]
Hmm, I can't reproduce the issue; can you check with the latest from the `main` branch? If that still doesn't work, would you mind sharing or linking to a complete (non-working) example I can inspect more directly?

Thanks!

**Comment by ChrilleSchappe** [comment]
Hello, Unfortunately I had an accident a week ago that make it rather painful to sit actually, so I have to postpone my answer a bit. I can’t send my whole application so I have to prepare something similar.  I’ll be back when I’m feeling better!/Christer8 dec. 2024 kl. 22:24 skrev Maxime Petazzoni ***@***.***>:﻿
Hmm, I can't reproduce the issue; can you check with the latest from the main branch? If that still doesn't work, would you mind sharing or linking to a complete (non-working) example I can inspect more directly?
Thanks!

**Comment by mpetazzoni** [comment]
Sorry to hear that, and I hope you feel better soon 🙏🏻. Ping this issue again when you have some time to look at it again!

**Comment by ycouble** [comment]
I had the same issue in v2.1.0 (version given in the readme docs on the repo root), switching to v2.1.2 fixed it.

**Comment by mpetazzoni** [comment]
Thanks @ycouble. @ChrilleSchappe Please try with 2.1.2 and feel free to re-open if you still have this issue.

**Comment by ChrilleSchappe** [comment]
Thanks, I will try that soon !/Christer9 jan. 2025 kl. 01:33 skrev Maxime Petazzoni ***@***.***>:﻿
Thanks @ycouble. @ChrilleSchappe Please try with 2.1.2 and feel free to re-open if you still have this issue.
